core/unpackaged/main/default/objects/Commerce_Search_Index__c/Commerce_Search_Index__c.object-meta.xml
<CustomObject>
    <label>Commerce Search Index</label>
    <nameField>
        <displayFormat>CSI-{000000000}</displayFormat>
        <label>Commerce Search Index Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commerce Search Indicies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

core/unpackaged/main/default/objects/Commerce_Search_Index__c/fields/Search_Phrases__c.field-meta.xml
<CustomField>
    <fullName>Search_Phrases__c</fullName>
    <label>Search Phrases</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

core/unpackaged/main/default/objects/Commerce_Search_Index__c/fields/Unique_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Product_Id__c</fullName>
    <externalId>true</externalId>
    <label>Unique Product Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

core/unpackaged/main/default/classes/ProductTriggerHandler_TEST.cls
/**
 * Copyright (c) 2024 ForeFront, Inc. All Rights Reserved.
 * Subject to ForeFront, Inc. licensing.
 *
 * @author pjendrzyca/forefront
 * @date 29.07.2024
 * @test ProductTriggerHandler_TEST_TEST
 * 
 **/

@IsTest
private class ProductTriggerHandler_TEST {
	@IsTest
	static void testBehavior() {
		// given
		Product2 product = new Product2(
			Name = 'test'
		);

		// when
		insert product;

		// then
		List<Commerce_Search_Index__c> indices = [
			SELECT Id, Unique_Product_Id__c, Search_Phrases__c FROM Commerce_Search_Index__c
		];

		Assert.areEqual(1, indices.size());
		Assert.areEqual(product.Id, indices[0].Unique_Product_Id__c);
		Assert.areEqual(product.Name, indices[0].Search_Phrases__c);


		// when
		product.Name = 'Changed Name';
		update product;

		Id oldIndexId = indices[0].Id;

		indices = [
			SELECT Id, Unique_Product_Id__c, Search_Phrases__c FROM Commerce_Search_Index__c
		];

		Assert.areEqual(1, indices.size(), 'should not create new index record');
		Assert.areEqual(oldIndexId, indices[0].Id, 'existing index should be updated');
		Assert.areEqual(product.Id, indices[0].Unique_Product_Id__c, 'product it should remain the same');
		Assert.areEqual(product.Name, indices[0].Search_Phrases__c, 'search phrase should be updated');
	}
}