core/unpackaged/main/default/objects/Order/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

core/unpackaged/main/default/objects/Order/fields/Integrated__c.field-meta.xml
<CustomField>
    <fullName>Integrated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>indicates if the order was sent to ERP successfully</description>
    <inlineHelpText>indicates if the order was sent to ERP successfully</inlineHelpText>
    <label>Integrated</label>
    <type>Checkbox</type>
</CustomField>

core/unpackaged/main/default/objects/Order/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <description>stores response message received for ERP orderCreate callout</description>
    <inlineHelpText>stores response message received for ERP orderCreate callout</inlineHelpText>
    <label>Integration Status</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

core/unpackaged/main/default/classes/OrderCreatedEventTriggerHandler_TEST.cls
/**
 * Copyright (c) 2024 ForeFront, Inc. All Rights Reserved.
 * Subject to ForeFront, Inc. licensing.
 *
 * @author pjendrzyca/Forefront
 * @date 13.03.2024
 * @description Test suite
 *
 */

@IsTest
private class OrderCreatedEventTriggerHandler_TEST {
	@IsTest(SeeAllData=true) // due to connect api limitations
	static void testBehavior() {
		// given
		Id orderSummaryId = XaCalloutController_TEST.createOrderSummary();
		Order order = [
			SELECT
				OriginalOrder.External_Id__c,
				OriginalOrder.Id
			FROM OrderSummary
			WHERE Id = :orderSummaryId
		].OriginalOrder;

		// external id and integrated field must be null
		// otherwise the order sending logic will not be triggered
		order.External_Id__c = null;
		order.Integrated__c = false;
		update order;

		// when
		Test.startTest();
		{
			EventBus.publish(new OrderSummaryCreatedEvent(
				OrderSummaryId = orderSummaryId,
				OrderId = order.Id
			));
		}
		Test.stopTest();

		// then
		OrderSummary updated = [
			SELECT Id,
				OriginalOrder.Integrated__c,
				OriginalOrder.Integration_Status__c
			FROM OrderSummary
			WHERE Id = :orderSummaryId
		];

		Assert.isFalse(updated.OriginalOrder.Integrated__c);
		Assert.isNotNull(updated.OriginalOrder.Integration_Status__c);
	}
}