core/unpackaged/main/default/objects/Order/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

core/unpackaged/main/default/objects/Order/fields/Integrated__c.field-meta.xml
<CustomField>
    <fullName>Integrated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>indicates if the order was sent to ERP successfully</description>
    <inlineHelpText>indicates if the order was sent to ERP successfully</inlineHelpText>
    <label>Integrated</label>
    <type>Checkbox</type>
</CustomField>

core/unpackaged/main/default/objects/Order/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <description>stores response message received for ERP orderCreate callout</description>
    <inlineHelpText>stores response message received for ERP orderCreate callout</inlineHelpText>
    <label>Integration Status</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

core/unpackaged/main/default/classes/OrderCreatedEventTriggerHandler.cls
/**
 * Copyright (c) 2024 ForeFront, Inc. All Rights Reserved.
 * Subject to ForeFront, Inc. licensing.
 *
 * @author pjendrzyca/Forefront
 * @description
 * @date 13.03.2024 <p/>
 * @test OrderCreatedEventTriggerHandler_TEST
 *
 */
public without sharing class OrderCreatedEventTriggerHandler extends TriggerHandler {
	protected override void afterInsert() {
		List<OrderSummaryCreatedEvent> created = Trigger.new;

		Set<Id> orderIds = Stream.of(created).ids(OrderSummaryCreatedEvent.OrderId);
		List<Order> orders = XaCalloutController.fetchOrders(orderIds);

		for(Order order : orders) {
			if(isOrderAlreadyIntegrated(order)) {
				continue;
			}

			try {
				ExternalService.XaApiService.putOrder_Response res = XaCalloutController.createOrder(order);

				order.Integrated__c = true;
				order.Integration_Status__c = res.Code202.message;
			}
			catch(Exception ex) {
				order.Integrated__c = false;
				order.Integration_Status__c = ex.getMessage() + '\n\n' + ex.getStackTraceString();
				Logger.error(ex.getMessage(), order, ex);
				Logger.saveLog();
			}
		}

		update orders;
	}

	private static Boolean isOrderAlreadyIntegrated(Order order) {
		return order.Integrated__c || String.isNotBlank(order.External_Id__c);
	}

}