core/unpackaged/main/default/objects/Order/fields/Integrated__c.field-meta.xml
<CustomField>
    <fullName>Integrated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>indicates if the order was sent to ERP successfully</description>
    <inlineHelpText>indicates if the order was sent to ERP successfully</inlineHelpText>
    <label>Integrated</label>
    <type>Checkbox</type>
</CustomField>

core/unpackaged/main/default/objects/Order/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <description>stores response message received for ERP orderCreate callout</description>
    <inlineHelpText>stores response message received for ERP orderCreate callout</inlineHelpText>
    <label>Integration Status</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

core/unpackaged/main/default/classes/SendOrderToXaController.cls
/**
 * Copyright (c) 2024 ForeFront, Inc. All Rights Reserved.
 * Subject to ForeFront, Inc. licensing.
 *
 * @author pjendrzyca/forefront
 * @date 22.10.2024
 * @test SendOrderToXaController_TEST
 * 
 **/

public with sharing class SendOrderToXaController {

	@AuraEnabled
	public static Boolean sendOrderToXa(Id orderId) {
		Order order = XaCalloutController.fetchOrder(orderId);

		try {
			ExternalService.XaApiService.putOrder_Response xaRes = XaCalloutController.createOrder(order);

			order.Integrated__c = true;
			order.Integration_Status__c = xaRes.Code202.message;

			update as system order;
			return true;

		} catch (Exception ex) {
			order.Integrated__c = false;
			order.Integration_Status__c = ex.getMessage() + '\n\n' + ex.getStackTraceString();

			update as system order;
			return false;
		}
	}
}