core/unpackaged/main/default/objects/Customer_Satisfaction__c/Customer_Satisfaction__c.object-meta.xml
<CustomObject>
    <label>Customer Satisfaction</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Customer Satisfaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Satisfactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

core/unpackaged/main/default/objects/Customer_Satisfaction__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

core/unpackaged/main/default/objects/Customer_Satisfaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Satsifactions</relationshipLabel>
    <relationshipName>Customer_Satsifactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

core/unpackaged/main/default/objects/Customer_Satisfaction__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Customer Satsifactions</relationshipLabel>
    <relationshipName>Customer_Satsifactions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

core/unpackaged/main/default/objects/Customer_Satisfaction__c/fields/Satisfied__c.field-meta.xml
<CustomField>
    <fullName>Satisfied__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Satisfied?</label>
    <type>Checkbox</type>
</CustomField>

core/unpackaged/main/default/classes/CustomerSatisfactionSurveyCtrl.cls
/**
	* Copyright (c) 2024 ForeFront, Inc. All Rights Reserved.
	* Subject to ForeFront, Inc. licensing.
	*
	* @author snguyen/Forefront
	* @version 1.0
	* @description
	*
	* PURPOSE
	* 
	*   Controller for CustomSatisfactionSurveyController
	* 
	* TEST CLASS 
	* 
	*   CustomSatisfactionSurveyController_TEST
	* 
	* CHANGE LOG 
	* 
	*    [Version; Date; Author; Description]
	*    v1.0; 3/22/2024; snguyen/Forefront; Initial Build
	* 
**/
public without sharing class CustomerSatisfactionSurveyCtrl {

    @AuraEnabled
    public static Boolean hasOrderAlreadyBeenReviewed(String orderNumber) {
        try {
            Id orderId = [SELECT OriginalOrderId FROM OrderSummary WHERE OrderNumber =: orderNumber].OriginalOrderId;

            return [SELECT COUNT() FROM Customer_Satisfaction__c WHERE Order__c =: orderId AND Contact__c =: BuyerService.currentContact.Id] > 0;
        } catch (Exception e) {
            throw new AuraHandledException(AuraHandledExceptionBuilder.buildClientMessage(e));
        }
    }

    @AuraEnabled
    public static void addCustomerSatisfaction(String orderNumber, Boolean isSatisfied, String comments) {
        try {
            Id orderId = [SELECT OriginalOrderId FROM OrderSummary WHERE OrderNumber =: orderNumber].OriginalOrderId;

            Customer_Satisfaction__c customerSatisfactionResponse = new Customer_Satisfaction__c(
                    Contact__c = BuyerService.currentContact.Id,
                    Order__c = orderId,
                    Comments__c = comments,
                    Satisfied__c = isSatisfied
            );
            insert customerSatisfactionResponse;
        } catch (Exception e) {
            throw new AuraHandledException(AuraHandledExceptionBuilder.buildClientMessage(e));
        }
    }
}