core/unpackaged/main/default/objects/LogEntry__c/LogEntry__c.object-meta.xml
<CustomObject>
    <description>Used by Nebula Logger to represent a single log message within a transaction - log entries can be generated via Apex, Flow, Process Builder, Lightning Web Components, and Aura Components.</description>
    <label>Log Entry</label>
    <nameField>
        <label>Entry ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Log Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

core/unpackaged/main/default/objects/LogEntry__c/fields/LoggingLevel__c.field-meta.xml
<CustomField>
    <fullName>LoggingLevel__c</fullName>
    <complianceGroup>PII;GDPR;CCPA</complianceGroup>
    <label>Logging Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LoggingLevel</valueSetName>
    </valueSet>
</CustomField>

core/unpackaged/main/default/objects/LogEntry__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <complianceGroup>None</complianceGroup>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

core/unpackaged/main/default/objects/LogEntry__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <complianceGroup>None</complianceGroup>
    <externalId>true</externalId>
    <label>Related Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

core/unpackaged/main/default/objects/LogEntry__c/fields/Tags__c.field-meta.xml
<CustomField>
    <fullName>Tags__c</fullName>
    <complianceGroup>None</complianceGroup>
    <label>Tags</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

core/unpackaged/main/default/classes/CommerceRepriceOpenCartsBatch_TEST.cls
/**
 * Copyright (c) 2024 ForeFront, Inc. All Rights Reserved.
 * Subject to ForeFront, Inc. licensing.
 *
 * @author pjendrzyca/Forefront
 * @description
 * @date 23/12/2024
 * @test CommerceRepriceOpenCartsBatch_TEST_TEST
 *
 */

@IsTest
private class CommerceRepriceOpenCartsBatch_TEST {

    @IsTest
    static void testBatch() {
        // given
        WebStore testWebStore = new WebStore(Name = 'Test Store');
        insert testWebStore;

        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;

        WebCart cartPrimary = new WebCart(
            Name = 'Cart Primary',
            Status = 'Active',
            AccountId = testAccount.Id,
            WebStoreId = testWebStore.Id
        );
        insert cartPrimary;

        WebCart cartSecondary = new WebCart(
            Name = 'Cart Secondary',
            Status = 'Active',
            IsSecondary = true,
            AccountId = testAccount.Id,
            WebStoreId = testWebStore.Id
        );
        insert cartSecondary;

        // when called without seeAllData true should fail to reprice
        Test.startTest();
        CommerceRepriceOpenCartsBatch batch = new CommerceRepriceOpenCartsBatch();
        Database.executeBatch(batch, 2);
        Test.stopTest();

        // then
        List<LogEntry__c> logs = [
            SELECT Message__c, LoggingLevel__c, RecordId__c, Tags__c
            FROM LogEntry__c
        ];
        Assert.isFalse(logs.isEmpty(), 'logs should be created.');

        Boolean hasError = false;

        for (LogEntry__c log : logs) {
            if (log.LoggingLevel__c == 'ERROR') {
                hasError = true;
                break;
            }
        }

        Assert.isTrue(hasError, 'Error log should be created.');
    }
}