core/unpackaged/main/default/objects/Lead/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

core/unpackaged/main/default/objects/Lead/fields/Cloned_From_Lead_Name__c.field-meta.xml
<CustomField>
    <fullName>Cloned_From_Lead_Name__c</fullName>
    <inlineHelpText>This is the Original Lead Name this Lead was cloned from</inlineHelpText>
    <label>Cloned From Lead Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/unpackaged/main/default/objects/Lead/fields/Cloned_To_Lead_Name__c.field-meta.xml
<CustomField>
    <fullName>Cloned_To_Lead_Name__c</fullName>
    <inlineHelpText>This is the New Lead that was created by cloning this lead</inlineHelpText>
    <label>Cloned To Lead Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/unpackaged/main/default/objects/Lead/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

core/unpackaged/main/default/objects/Lead/fields/Has_Been_Cloned__c.field-meta.xml
<CustomField>
    <fullName>Has_Been_Cloned__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates if a lead has been cloned to another lead</inlineHelpText>
    <label>Has Been Cloned</label>
    <type>Checkbox</type>
</CustomField>

core/unpackaged/main/default/objects/Lead/fields/Is_Cloned_Lead__c.field-meta.xml
<CustomField>
    <fullName>Is_Cloned_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This indicates if a Lead has been cloned from another lead.</inlineHelpText>
    <label>Is Cloned Lead</label>
    <type>Checkbox</type>
</CustomField>

core/unpackaged/main/default/objects/Lead/fields/Lead_Queue__c.field-meta.xml
<CustomField>
    <fullName>Lead_Queue__c</fullName>
    <label>Lead Queue</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Queue</valueSetName>
    </valueSet>
</CustomField>

core/unpackaged/main/default/globalValueSets/Lead_Queue.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pulley Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Idler Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Pulley Project</fullName>
    </customValue>
    <customValue>
        <fullName>Idler Project</fullName>
    </customValue>
    <customValue>
        <fullName>Order Support</fullName>
    </customValue>
    <customValue>
        <fullName>Inside Sales Temp Inbox</fullName>
    </customValue>
    <customValue>
        <fullName>ISA Same Day</fullName>
    </customValue>
    <customValue>
        <fullName>West 35</fullName>
    </customValue>
    <customValue>
        <fullName>West 26</fullName>
    </customValue>
    <customValue>
        <fullName>West 15</fullName>
    </customValue>
    <customValue>
        <fullName>Central 3</fullName>
    </customValue>
    <customValue>
        <fullName>Central 9</fullName>
    </customValue>
    <customValue>
        <fullName>Central 16</fullName>
    </customValue>
    <customValue>
        <fullName>Central 14</fullName>
    </customValue>
    <customValue>
        <fullName>Central 24</fullName>
    </customValue>
    <customValue>
        <fullName>East 4</fullName>
    </customValue>
    <customValue>
        <fullName>East 21</fullName>
    </customValue>
    <customValue>
        <fullName>East 11</fullName>
    </customValue>
    <customValue>
        <fullName>East 33</fullName>
    </customValue>
    <customValue>
        <fullName>KeyAcct1</fullName>
    </customValue>
    <customValue>
        <fullName>KeyAcct2</fullName>
    </customValue>
    <customValue>
        <fullName>Floater</fullName>
    </customValue>
    <customValue>
        <fullName>eCommerce</fullName>
    </customValue>
    <customValue>
        <fullName>OIC Queue</fullName>
    </customValue>
    <customValue>
        <fullName>Key Accounts</fullName>
    </customValue>
    <masterLabel>Lead Queue</masterLabel>
</GlobalValueSet>

core/unpackaged/main/default/classes/LeadTriggerHandlerTest.cls
@IsTest
private class LeadTriggerHandlerTest {
  @TestSetup
  static void makeData() {
    Account testAccount = new Account();
    testAccount.Name = 'Test';
    insert testAccount;

    Contact testContact = new Contact();
    testContact.LastName = 'Test';
    testContact.AccountId = testAccount.Id;
    insert testContact;

    Lead testLead = new Lead();
    testLead.Account__c = testAccount.Id;
    testLead.Contact__c = testContact.Id;
    testLead.Company = 'Test';
    testLead.LastName = 'Test';
    testLead.Lead_Queue__c = 'Pulley Daily';
    insert testLead;
  }

  @IsTest
  static void testCloneLead() {
    Lead testLead = [
      SELECT Id, Account__c, Contact__c, Company, LastName, Lead_Queue__c
      FROM Lead
      LIMIT 1
    ];
    Lead newLead = testLead.clone(false, true, false, false);

    Test.startTest();
    insert newLead;
    Test.stopTest();

    Lead testLeadAfterTrigger = [
      SELECT
        Id,
        Name,
        Has_Been_Cloned__c,
        Cloned_To_Lead_Name__c,
        Cloned_From_Lead_Name__c,
        Is_Cloned_Lead__c
      FROM Lead
      WHERE Id = :testLead.Id
    ];
    Lead newLeadAfterTrigger = [
      SELECT
        Id,
        Name,
        Has_Been_Cloned__c,
        Cloned_To_Lead_Name__c,
        Cloned_From_Lead_Name__c,
        Is_Cloned_Lead__c
      FROM Lead
      WHERE Id = :newLead.Id
    ];

    Assert.isTrue(
      testLeadAfterTrigger.Has_Been_Cloned__c,
      'Lead should be marked as having been cloned'
    );
    Assert.isTrue(
      newLeadAfterTrigger.Is_Cloned_Lead__c,
      'New Lead should be marked as a cloned lead.'
    );
  }
}