core/unpackaged/main/default/objects/Lead/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

core/unpackaged/main/default/objects/Lead/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

core/unpackaged/main/default/objects/Lead/fields/Lead_Queue__c.field-meta.xml
<CustomField>
    <fullName>Lead_Queue__c</fullName>
    <label>Lead Queue</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Queue</valueSetName>
    </valueSet>
</CustomField>

core/unpackaged/main/default/objects/Opportunity/fields/Lead_Queue__c.field-meta.xml
<CustomField>
    <fullName>Lead_Queue__c</fullName>
    <inlineHelpText>Lead Queue responsible for managing assignment and follow up related to this opportunity. Queue is selected based off of email opportunity comes in from. Please ensure correct lead is chosen to help with proper routing and tracking of sales efforts.</inlineHelpText>
    <label>Lead Queue</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Queue</valueSetName>
    </valueSet>
</CustomField>

core/unpackaged/main/default/globalValueSets/Lead_Queue.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pulley Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Idler Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Pulley Project</fullName>
    </customValue>
    <customValue>
        <fullName>Idler Project</fullName>
    </customValue>
    <customValue>
        <fullName>Order Support</fullName>
    </customValue>
    <customValue>
        <fullName>Inside Sales Temp Inbox</fullName>
    </customValue>
    <customValue>
        <fullName>ISA Same Day</fullName>
    </customValue>
    <customValue>
        <fullName>West 35</fullName>
    </customValue>
    <customValue>
        <fullName>West 26</fullName>
    </customValue>
    <customValue>
        <fullName>West 15</fullName>
    </customValue>
    <customValue>
        <fullName>Central 3</fullName>
    </customValue>
    <customValue>
        <fullName>Central 9</fullName>
    </customValue>
    <customValue>
        <fullName>Central 16</fullName>
    </customValue>
    <customValue>
        <fullName>Central 14</fullName>
    </customValue>
    <customValue>
        <fullName>Central 24</fullName>
    </customValue>
    <customValue>
        <fullName>East 4</fullName>
    </customValue>
    <customValue>
        <fullName>East 21</fullName>
    </customValue>
    <customValue>
        <fullName>East 11</fullName>
    </customValue>
    <customValue>
        <fullName>East 33</fullName>
    </customValue>
    <customValue>
        <fullName>KeyAcct1</fullName>
    </customValue>
    <customValue>
        <fullName>KeyAcct2</fullName>
    </customValue>
    <customValue>
        <fullName>Floater</fullName>
    </customValue>
    <customValue>
        <fullName>eCommerce</fullName>
    </customValue>
    <customValue>
        <fullName>OIC Queue</fullName>
    </customValue>
    <customValue>
        <fullName>Key Accounts</fullName>
    </customValue>
    <masterLabel>Lead Queue</masterLabel>
</GlobalValueSet>

core/unpackaged/main/default/classes/xStudio_LeadConversionTest.cls
@IsTest
private class xStudio_LeadConversionTest {
    @IsTest
    static void shouldReturnConvertedLead() {
        Account testAccount = new Account();
        testAccount.Name = 'Test';
        insert testAccount;

        Contact testContact = new Contact();
        testContact.LastName = 'Test';
        testContact.AccountId = testAccount.Id;
        insert testContact;
        
        Lead testLead = new Lead();
        testLead.Account__c = testAccount.Id;
        testLead.Contact__c = testContact.Id;
        testLead.Company = 'Test';
        testLead.LastName = 'Test';
        testLead.Lead_Queue__c = 'Pulley Daily';
        insert testLead;

        List<Lead> leadList = new List<Lead>();
        leadList.add(testLead);

        Test.startTest();
        List<Id> newOpportunityIds = xStudio_LeadConversion.convertLeadsToOpportunitys(leadList);
        Test.stopTest();

        Assert.isTrue(newOpportunityIds.size() > 0, 'Opportunity should have been created.');
    }
}