core/unpackaged/main/default/objects/Account/fields/companyNumber__c.field-meta.xml
<CustomField>
    <fullName>companyNumber__c</fullName>
    <label>Company Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

core/unpackaged/main/default/objects/Account/fields/externalId__c.field-meta.xml
<CustomField>
    <fullName>externalId__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

core/unpackaged/main/default/objects/Account/fields/Indirect_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Indirect_Customer_No__c</fullName>
    <inlineHelpText>Indirect Customer Code number associated with Account. Created when pricing is programmed</inlineHelpText>
    <label>Indirect Customer No</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

core/unpackaged/main/default/objects/Contact/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

core/unpackaged/main/default/objects/Order/fields/Allow_Split_Shipment__c.field-meta.xml
<CustomField>
    <fullName>Allow_Split_Shipment__c</fullName>
    <defaultValue>true</defaultValue>
    <description>indicates if user agreed to split shipment his order if it couldn't be fulfilled complete</description>
    <inlineHelpText>indicates if user agreed to split shipment his order if it couldn't be fulfilled complete</inlineHelpText>
    <label>Allow Split Shipment</label>
    <type>Checkbox</type>
</CustomField>

core/unpackaged/main/default/objects/Order/fields/Carrier_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Account_Number__c</fullName>
    <label>Carrier Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/unpackaged/main/default/objects/Order/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

core/unpackaged/main/default/objects/Order/fields/Integrated__c.field-meta.xml
<CustomField>
    <fullName>Integrated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>indicates if the order was sent to ERP successfully</description>
    <inlineHelpText>indicates if the order was sent to ERP successfully</inlineHelpText>
    <label>Integrated</label>
    <type>Checkbox</type>
</CustomField>

core/unpackaged/main/default/objects/Order/fields/Logistics_Information__c.field-meta.xml
<CustomField>
    <fullName>Logistics_Information__c</fullName>
    <label>Logistics Information</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

core/unpackaged/main/default/objects/Order/fields/Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Ship_Date__c</fullName>
    <description>Ship Date Integrated from ERP</description>
    <label>Ship Date</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

core/unpackaged/main/default/objects/Order/fields/Third_Party_Billing_Company__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Billing_Company__c</fullName>
    <label>Third Party Billing Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/unpackaged/main/default/objects/Order/fields/Third_Party_Billing_Street1__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Billing_Street1__c</fullName>
    <label>Third Party Billing Street1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/unpackaged/main/default/objects/Order/fields/Third_Party_Billing_Street2__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Billing_Street2__c</fullName>
    <label>Third Party Billing Street2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/unpackaged/main/default/objects/OrderDeliveryGroup/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>BLANKVALUE(DeliverToCompanyName, BLANKVALUE(DeliverToName, BLANKVALUE(DeliverToFullFirstName, BLANKVALUE(DeliverToFullLastName, 'N/A'))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company</label>
    <type>Text</type>
</CustomField>

core/unpackaged/main/default/objects/OrderDeliveryGroup/fields/Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Ship_Date__c</fullName>
    <label>Ship Date</label>
    <type>Date</type>
</CustomField>

core/unpackaged/main/default/objects/OrderDeliveryGroup/fields/Ship_Option__c.field-meta.xml
<CustomField>
    <fullName>Ship_Option__c</fullName>
    <label>Ship Option</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/unpackaged/main/default/objects/OrderItem/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>customer notes</description>
    <inlineHelpText>customer notes</inlineHelpText>
    <label>Notes</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

core/unpackaged/main/default/objects/OrderSummary/fields/Allow_Split_Shipment__c.field-meta.xml
<CustomField>
    <fullName>Allow_Split_Shipment__c</fullName>
    <defaultValue>true</defaultValue>
    <description>indicates if user agreed to split shipment his order if it couldn't be fulfilled complete</description>
    <inlineHelpText>indicates if user agreed to split shipment his order if it couldn't be fulfilled complete</inlineHelpText>
    <label>Allow Split Shipment</label>
    <type>Checkbox</type>
</CustomField>

core/unpackaged/main/default/objects/OrderSummary/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <label>Carrier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/unpackaged/main/default/objects/OrderSummary/fields/Carrier_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Account_Number__c</fullName>
    <label>Carrier Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/unpackaged/main/default/objects/OrderSummary/fields/Logistics_Information__c.field-meta.xml
<CustomField>
    <fullName>Logistics_Information__c</fullName>
    <label>Logistics Information</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

core/unpackaged/main/default/objects/OrderSummary/fields/Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Ship_Date__c</fullName>
    <formula>MID(OriginalOrder.Ship_Date__c, 6, 2) &amp; "/" &amp;
MID(OriginalOrder.Ship_Date__c, 9, 2) &amp; "/" &amp;
LEFT(OriginalOrder.Ship_Date__c, 4)</formula>
    <label>Ship Date</label>
    <type>Text</type>
</CustomField>

core/unpackaged/main/default/objects/OrderSummary/fields/Third_Party_Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Billing_City__c</fullName>
    <label>Third Party Billing City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/unpackaged/main/default/objects/OrderSummary/fields/Third_Party_Billing_Company__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Billing_Company__c</fullName>
    <label>Third Party Billing Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/unpackaged/main/default/objects/OrderSummary/fields/Third_Party_Billing_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Billing_Postal_Code__c</fullName>
    <label>Third Party Billing Postal Code</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

core/unpackaged/main/default/objects/OrderSummary/fields/Third_Party_Billing_StateCode__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Billing_StateCode__c</fullName>
    <label>Third Party Billing StateCode</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

core/unpackaged/main/default/objects/OrderSummary/fields/Third_Party_Billing_Street1__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Billing_Street1__c</fullName>
    <label>Third Party Billing Street1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/unpackaged/main/default/objects/OrderSummary/fields/Third_Party_Billing_Street2__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Billing_Street2__c</fullName>
    <label>Third Party Billing Street2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/unpackaged/main/default/objects/Product2/fields/external_ID__c.field-meta.xml
<CustomField>
    <fullName>external_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

core/unpackaged/main/default/classes/XaCalloutController.cls
/**
 * Copyright (c) 2024 ForeFront, Inc. All Rights Reserved.
 * Subject to ForeFront, Inc. licensing.
 *
 * @author pjendrzyca/Forefront
 * @description
 * @date 11.03.2024 <p/>
 * @test XaCalloutController_TEST
 *
 */

public without sharing class XaCalloutController {

    public static final String DELIVERY_METHOD_THIRD_PARTY = '3rd Party Bill To Address';

    @AuraEnabled
    public static List<ExternalService.XaApiService_getItemInventoryByItemNumber_OUT_200> fetchInventory(Id productId) {

        String productCode = [
            SELECT Id,
                ProductCode
            FROM Product2
            WHERE Id = :productId
            WITH SYSTEM_MODE
        ]?.ProductCode;

        ExternalService.XaApiService service = new ExternalService.XaApiService();

        ExternalService.XaApiService.getItemInventoryByItemNumber_Request request =
            new ExternalService.XaApiService.getItemInventoryByItemNumber_Request();

        request.itemNumber = productCode;

        ExternalService.XaApiService.getItemInventoryByItemNumber_Response response =
            service.getItemInventoryByItemNumber(request);

        return response.Code200;
    }

    @AuraEnabled
    public static Boolean canFulfillOrder(Id checkoutId, ExternalService.XaApiService_Address shippingAddress) {

        Id cartId = [
            SELECT WebCartId
            FROM CartCheckoutSession
            WHERE Id = :checkoutId
            WITH SYSTEM_MODE
        ].WebCartId;

        List<CartItem> items = [
            SELECT Id,
                Product2.ProductCode,
                Quantity
            FROM CartItem
            WHERE CartId = :cartId
            AND Type = 'Product'
            WITH SYSTEM_MODE
        ];

        if (items.size() > 1 || items.get(0).Quantity > 1) {
            List<ExternalService.XaApiService_postAvailableToAssemble_IN_body_items> requestItems =
                    new List<ExternalService.XaApiService_postAvailableToAssemble_IN_body_items>();

            for (CartItem cartItem : items) {
                ExternalService.XaApiService_postAvailableToAssemble_IN_body_items requestItem =
                        new ExternalService.XaApiService_postAvailableToAssemble_IN_body_items();

                requestItem.itemNumber = cartItem.Product2.ProductCode;
                requestItem.quantity = cartItem.Quantity.intValue();

                requestItems.add(requestItem);
            }


            ExternalService.XaApiService service = new ExternalService.XaApiService();

            ExternalService.XaApiService.postAvailableToAssemble_Request request =
                    new ExternalService.XaApiService.postAvailableToAssemble_Request();

            request.body = new ExternalService.XaApiService_postAvailableToAssemble_IN_body();
            request.body.items = requestItems;
            request.body.shippingAddress = shippingAddress;

            ExternalService.XaApiService.postAvailableToAssemble_Response response =
                    service.postAvailableToAssemble(request);

            return response.Code200?.canFulfill ?? false; // todo: how do we want to handle errors?
        } else {
            return true;
        }
    }

    @AuraEnabled
    public static String createContact(Contact contact) {

        ExternalService.XaApiService service = new ExternalService.XaApiService();
        ExternalService.XaApiService.putContactByCustomerNumberAndEmail_Request req =
            new ExternalService.XaApiService.putContactByCustomerNumberAndEmail_Request();

        req.customerNumber = createCustomerNumberFromAccount(contact.Account);
        req.email = contact.Email;
        req.body = new ExternalService.XaApiService_putContactByCustomerNumberAndEmail_IN_body();
        req.body.name = contact.Name;

        ExternalService.XaApiService.putContactByCustomerNumberAndEmail_Response res =
            service.putContactByCustomerNumberAndEmail(req);

        return res.Code201;
    }

    @AuraEnabled
    public static String fetchInvoice(Id orderSummaryId) {

        Order order = [
            SELECT OriginalOrder.External_Id__c
            FROM OrderSummary
            WHERE Id = :orderSummaryId
            WITH SYSTEM_MODE
        ]?.OriginalOrder;

        ExternalService.XaApiService service = new ExternalService.XaApiService();

        ExternalService.XaApiService.getOrderSalesforceInvoiceByExternalID_Request req =
            new ExternalService.XaApiService.getOrderSalesforceInvoiceByExternalID_Request();

        req.externalID = String.valueOf(order.External_Id__c);

        ExternalService.XaApiService.getOrderSalesforceInvoiceByExternalID_Response res =
            service.getOrderSalesforceInvoiceByExternalID(req);

        return res.Code200.invoicePDF;
    }

    @AuraEnabled
    public static ExternalService.XaApiService.putOrder_Response createOrder(Order order) {

        ExternalService.XaApiService service = new ExternalService.XaApiService();
        ExternalService.XaApiService.putOrder_Request req = prepareOrderRequest(order);

        Logger.info('Sending order to XA: ' + JSON.serialize(req))
            .setRecord(order.Id);
        
        ExternalService.XaApiService.putOrder_Response res = new ExternalService.XaApiService.putOrder_Response();

        try {
            res = service.putOrder(req);
            Logger.info('Received response from XA: ' + JSON.serialize(res))
            .setRecord(order.Id);
        } catch (Exception e) {
            Logger.error('Error sending order to XA: ' + e.getMessage())
                .setRecord(order.Id);
        }

        Logger.saveLog();

        return res;
    }

    public static String createCustomerNumberFromAccount(Account account) {
        if (account?.externalId__c == null && account?.Parent?.externalId__c == null) {
            throw new XaCalloutException('Account must have external id populated for this call');
        }

        String externalId = '' + (account.externalId__c ?? account?.Parent?.externalId__c);

        return externalId.left(externalId.length() - 2) + '-' + externalId.right(2);
    }

    public static Order fetchOrder(Id orderId) {
        return fetchOrders(new Set<Id>{orderId})[0];
    }

    public static List<Order> fetchOrders(Set<Id> orderIds) {
        return [
            SELECT Id,
                Account.externalId__c,
                Account.Parent.externalId__c,
                Account.companyNumber__c,
                // ADDED 06_10_26 by Ian Moore: Fetch Indirect Customer Code from Account
                Account.Indirect_Customer_No__c,
                CreatedBy.Name,
                CreatedBy.Email,
                PoNumber,
                OrderedDate,
                Owner.Name,
                External_Id__c,
                Integrated__c,
                BillingStreet,
                BillingCity,
                BillingStateCode,
                BillingPostalCode,
                Third_Party_Billing_Street1__c,
                Third_Party_Billing_Street2__c,
                Third_Party_Billing_City__c,
                Third_Party_Billing_Company__c,
                Third_Party_Billing_StateCode__c,
                Third_Party_Billing_Postal_Code__c,
                Allow_Split_Shipment__c,
                /* NEW: carrier fields on Order */
                Carrier__c,
                Carrier_Account_Number__c,
                Logistics_Information__c, (
                SELECT Id,
                    LineNumber,
                    Notes__c,
                    Product2.ProductCode,
                    Quantity,
                    UnitPrice
                FROM OrderItems
                WHERE Type = 'Order Product'
            ), (
                SELECT Id,
                    OrderDeliveryMethod.Name,
                    DeliverToName,
                    DeliveryInstructions,
                    DeliverToCompanyName,
                    DeliverToFullFirstName,
                    DeliverToFullLastName,
                    DeliverToStreet,
                    DeliverToCity,
                    DeliverToStateCode,
                    DeliverToPostalCode,
                    Ship_Date__c,
                    Company__c,
                    Ship_Option__c
                FROM OrderDeliveryGroups
            ), (
                SELECT Id,
                    ContentDocument.LatestPublishedVersion.VersionData,
                    ContentDocument.LatestPublishedVersion.Title,
                    ContentDocument.LatestPublishedVersion.FileType,
                    ContentDocument.LatestPublishedVersion.FileExtension
                FROM ContentDocumentLinks
                LIMIT 1
            )
            FROM Order
            WHERE Id IN :orderIds
            WITH SYSTEM_MODE
        ];
    }

    private static ExternalService.XaApiService.putOrder_Request prepareOrderRequest(Order order) {
        ExternalService.XaApiService.putOrder_Request req = new ExternalService.XaApiService.putOrder_Request();
        req.body = new ExternalService.XaApiService_Order();

        req.body.customerNumber = createCustomerNumberFromAccount(order.Account);
        // ADDED 06_10_26 by Ian Moore: Set indirectCustomerID from Account's Indirect Customer Code Field,
        // sent immediately after customerNumber to match required XA message structure for Indirect Customers.
        if (order.Account.Indirect_Customer_No__c != null) {
            req.body.indirectCustomerID = Integer.valueOf(order.Account.Indirect_Customer_No__c);
        }
        req.body.orderTime = order.OrderedDate;

        req.body.createdBy = new ExternalService.XaApiService_Order_createdBy();
        req.body.createdBy.name = order.CreatedBy.Name;
        req.body.createdBy.email = order.CreatedBy.Email;

        req.body.z0currency = 'USD';
        req.body.referenceOrder = order.Id;

        req.body.purchaseOrder = new ExternalService.XaApiService_Order_purchaseOrder();
        req.body.purchaseOrder.z0number = order.PoNumber;

        if(hasPoDocumentAttached(order)) {
            ContentVersion poDocument = order.ContentDocumentLinks[0].ContentDocument.LatestPublishedVersion;

            req.body.purchaseOrder.document = EncodingUtil.base64Encode(poDocument.VersionData);
            req.body.purchaseOrder.documentType = poDocument.FileExtension;
        }

        req.body.lineItems = new List<ExternalService.XaApiService_LineItem>();

        for (OrderItem item : order.OrderItems) {
            ExternalService.XaApiService_LineItem reqItem = new ExternalService.XaApiService_LineItem();

            reqItem.itemNumber = item.Product2.ProductCode;
            reqItem.quantity = item.Quantity.intValue();
            reqItem.unitPrice = item.UnitPrice;
            reqItem.lineNumber = item.LineNumber;
            reqItem.tag = item.Notes__c ?? 'N/A';

            req.body.lineItems.add(reqItem);
        }

        OrderDeliveryGroup deliveryGroup = order.OrderDeliveryGroups[0];

        req.body.shipping = new ExternalService.XaApiService_Order_shipping();
        req.body.shipping.delivery = deliveryGroup.Ship_Option__c ?? '';
        req.body.shipping.shipVia = deliveryGroup.OrderDeliveryMethod.Name;
        
        Date shipDate = deliveryGroup.Ship_Date__c ?? Date.today();
        req.body.shipping.requestedShipDate =
        DateTime.newInstance(shipDate, Time.newInstance(0, 0, 0, 0));  
        
        req.body.shipping.shippingAddress = new ExternalService.XaApiService_Address();
        req.body.shipping.shippingAddress.contact = deliveryGroup.Company__c;
        req.body.shipping.shippingAddress.city = deliveryGroup.DeliverToCity ?? '';
        req.body.shipping.shippingAddress.street1 = deliveryGroup.DeliverToStreet ?? '';
        req.body.shipping.shippingAddress.state = deliveryGroup.DeliverToStateCode ?? '';
        req.body.shipping.shippingAddress.zip = deliveryGroup.DeliverToPostalCode ?? '';
        String shippingInstructions = (order.Logistics_Information__c != null ? order.Logistics_Information__c + ' ' : '') + (deliveryGroup.DeliveryInstructions ?? '');
        req.body.shipping.shippingInstructions = shippingInstructions;
        req.body.shipping.carrier = order.Carrier__c ?? '';
        req.body.shipping.carrierAccountNumber = order.Carrier_Account_Number__c ?? '';

        if (DELIVERY_METHOD_THIRD_PARTY.equalsIgnoreCase(deliveryGroup.OrderDeliveryMethod.Name)) {
            req.body.shipping.freightBillingAddress = new ExternalService.XaApiService_Address();

            req.body.shipping.freightBillingAddress.contact = order.Third_Party_Billing_Company__c ?? '';
            req.body.shipping.freightBillingAddress.city = order.Third_Party_Billing_City__c ?? '';
            req.body.shipping.freightBillingAddress.street1 = order.Third_Party_Billing_Street1__c ?? '';
            req.body.shipping.freightBillingAddress.street2 = order.Third_Party_Billing_Street2__c ?? '';
            req.body.shipping.freightBillingAddress.state = order.Third_Party_Billing_StateCode__c ?? '';
            req.body.shipping.freightBillingAddress.zip = order.Third_Party_Billing_Postal_Code__c ?? '';
        }

        req.body.allowSplitShipments = order.Allow_Split_Shipment__c;

        return req;
    }

    
    public static BulkItemPricingResponse fetchBulkItemPricingByCustomerNumber(String customerNumber, Decimal indirectCustomerId, List<String> productCodes) {
        Http h = new Http();
        HttpRequest req = new HttpRequest();
        String endpointString = 'callout:XA_API/item/pricing/'+customerNumber;
        if(indirectCustomerId != null) {
            endpointString += '?indirectCustomerID='+indirectCustomerId.round(System.RoundingMode.FLOOR);
        }
        req.setEndpoint(endpointString);
        req.setMethod('POST');
        List<Map<String,String>> postBody = new List<Map<String,String>>();
        for(String productCode : productCodes) {
            Map<String,String> codeMap = new Map<String,String>();
            codeMap.put('itemNumber', productCode);
            postBody.add(codeMap);
        }
        req.setBody(JSON.serialize(postBody));
        HttpResponse res = h.send(req);
        return (BulkItemPricingResponse) JSON.deserialize(res.getBody(), BulkItemPricingResponse.class);
    }

    private static Boolean hasPoDocumentAttached(Order order) {
        return !order.ContentDocumentLinks.isEmpty();
    }

    public class XaCalloutException extends Exception {
    }

    public class BulkItemPricingResponse {
        public String[] errors;
        public BulkItemPricing[] items;
    }

    public class BulkItemPricing {
        public String itemNumber;
        public Double listPrice;
        public Double sellPrice;
    }
}