core/unpackaged/main/default/objects/Account/fields/companyNumber__c.field-meta.xml
<CustomField>
    <fullName>companyNumber__c</fullName>
    <label>Company Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

core/unpackaged/main/default/objects/Account/fields/externalId__c.field-meta.xml
<CustomField>
    <fullName>externalId__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

core/unpackaged/main/default/objects/Contact/fields/XA_Integrated__c.field-meta.xml
<CustomField>
    <fullName>XA_Integrated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>indicates if contact was successfully sent to XA</description>
    <inlineHelpText>indicates if contact was successfully sent to XA</inlineHelpText>
    <label>XA Integrated</label>
    <type>Checkbox</type>
</CustomField>

core/unpackaged/main/default/objects/Contact/fields/XA_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>XA_Integration_Status__c</fullName>
    <description>integration status received from XA when contact create call was made</description>
    <inlineHelpText>integration status received from XA when contact create call was made</inlineHelpText>
    <label>XA Integration Status</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

core/unpackaged/main/default/classes/XaContactIntegrationScheduledJob.cls
/**
 * Copyright (c) 2024 ForeFront, Inc. All Rights Reserved.
 * Subject to ForeFront, Inc. licensing.
 *
 * @author pjendrzyca/Forefront
 * @description
 * @date 15.03.2024 <p/>
 * @test XaContactIntegrationScheduledJob_TEST
 *
 */

public with sharing class XaContactIntegrationScheduledJob implements
		Database.Batchable<SObject>,
		Database.Stateful,
		Database.AllowsCallouts,
		Schedulable
{

	private final static String CRON_HOURLY_INTERVAL = '0 0 * * * ?';
	private final static Integer MAX_BATCH_SIZE = 1;

	private final String transactionID = Logger.getTransactionId();

	public static Id scheduleToRunHourly() {
		final String jobName = Test.isRunningTest()
			? 'TestXaContactIntegrationJob'
			: 'XaContactIntegrationJob';

		return System.schedule(jobName, CRON_HOURLY_INTERVAL, new XaContactIntegrationScheduledJob());
	}

	@TestVisible
	private XaContactIntegrationScheduledJob() {}

	public Database.QueryLocator start(Database.BatchableContext context) {
		return Database.getQueryLocator([
			SELECT Id,
				Name,
				Email,
				Account.companyNumber__c,
				Account.externalId__c,
				Account.Parent.externalId__c
			FROM Contact
			WHERE XA_Integrated__c = FALSE
			AND CreatedDate >=: Datetime.now().addHours(-1).addMinutes(-10) // accounting for sched job delays
		]);
	}

	public void execute(Database.BatchableContext context, List<Contact> contacts) {
		// batch size will be always 1
		Contact contact = contacts[0];
		Logger.setParentLogTransactionId(transactionID);

		try {
			String res = XaCalloutController.createContact(contact);
			contact.XA_Integration_Status__c = res;
			contact.XA_Integrated__c = true;

			Logger.info('Contact successfully integrated').setRecord(contact.Id);
		}
		catch (Exception ex) {
			contact.XA_Integrated__c = false;
			contact.XA_Integration_Status__c = ex.getMessage();

			Logger.error('Contact failed to be integrated', ex).setRecord(contact.Id);
		}
		finally {
			Logger.saveLog();
		}

		update contact;
	}

	public void finish(Database.BatchableContext context) {}


	public void execute(SchedulableContext context) {
		Database.executeBatch(this, MAX_BATCH_SIZE);
	}
}