core/unpackaged/main/default/objects/Account/fields/companyNumber__c.field-meta.xml
<CustomField>
    <fullName>companyNumber__c</fullName>
    <label>Company Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

core/unpackaged/main/default/objects/Account/fields/externalId__c.field-meta.xml
<CustomField>
    <fullName>externalId__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

core/unpackaged/main/default/classes/ExternalManagedAccountControllerTest.cls
@IsTest
private class ExternalManagedAccountControllerTest {
    @IsTest
    static void getCurrentExternalAccountName_success() {
        b2btd.xAccount testAccount = new b2btd.xAccount();
        testAccount.persist();
        b2btd.xContact testContact = new b2btd.xContact();
        testContact.withAccount(testAccount);
        testContact.persist();
        b2btd.xUser testUser = new b2btd.xUser();
        testUser.buyer(testContact);
        testUser.persist();

        b2btd.xAccount externalAccount = new b2btd.xAccount();
        externalAccount.set(Account.externalId__c, 43532.00);
        externalAccount.set(Account.companyNumber__c, 5);
        externalAccount.persist();

        Account expectedAccount = (Account) externalAccount.getRecord();
        User expectedUser = (User) testUser.getRecord();
        DelegatedAccount da = new DelegatedAccount();
        da.TargetId = expectedAccount.Id;
        da.Name = 'Test Account';
        da.ManagedById = expectedUser.Id;
        insert da;

        Test.startTest();
        String actualAccountName = ExternalManagedAccountController.getCurrentExternalAccountName(expectedAccount.Id);
        Assert.areEqual('Test Account', actualAccountName);
        Test.stopTest();
    }

    @IsTest
    static void getCurrentExternalAccountName_fail() {
        b2btd.xAccount testAccount = new b2btd.xAccount();
        testAccount.persist();
        b2btd.xContact testContact = new b2btd.xContact();
        testContact.withAccount(testAccount);
        testContact.persist();
        b2btd.xUser testUser = new b2btd.xUser();
        testUser.buyer(testContact);
        testUser.persist();

        b2btd.xAccount externalAccount = new b2btd.xAccount();
        externalAccount.set(Account.externalId__c, 43532.00);
        externalAccount.set(Account.companyNumber__c, 5);
        externalAccount.persist();

        Account expectedAccount = (Account) externalAccount.getRecord();
        User expectedUser = (User) testUser.getRecord();

        Test.startTest();
        try {
            String actualAccountName = ExternalManagedAccountController.getCurrentExternalAccountName(expectedAccount.Id);
        } catch (Exception e) {
            Assert.isNotNull(e);
        }
        Test.stopTest();
    }
}